name = "pic-christmas-godmode"
compatibility_date = "2024-11-01"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".next"

[vars]
NEXT_PUBLIC_TURNSTILE_SITEKEY = "0x4AAAAAAAY4Q_Y_Q_Y_Q_Y_Q"
